// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // schema: "prisma/schema.prisma", // for single prisma schema file
  schema: "prisma/schema", // for multiple prisma schema files
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // url: env("DATABASE_URL"),
    url: "postgres://b9f7961c65734f5cf002223d8493abe5675b0a78ccf1d7775195323fefea44f1:sk_HYDjCKwNYTEbb9vo64oy2@pooled.db.prisma.io:5432/postgres?sslmode=require",
  },
});
